---
- name: Common OS baseline
  hosts: fleet_all
  become: true
  roles:
    - common

- name: Install Docker where Docker Compose is used
  hosts:
    - fleet_app
    - fleet_db
  become: true
  roles:
    - docker

- name: Deploy MySQL for Fleet
  hosts: fleet_db
  become: true
  roles:
    - fleet_mysql

- name: Deploy Redis for Fleet
  hosts: fleet_redis
  become: true
  roles:
    - fleet_redis

- name: Deploy Fleet app
  hosts: fleet_app
  become: true
  roles:
    - fleet_app
