all:
  children:
    fleet_app:
      hosts:
        fleet-app-dev:
          ansible_host: 192.168.50.11
    fleet_db:
      hosts:
        fleet-db-dev:
          ansible_host: 192.168.50.12
    fleet_redis:
      hosts:
        fleet-redis-dev:
          ansible_host: 192.168.50.13
