---
- name: Install Redis
  ansible.builtin.apt:
    name: redis-server
    state: present

- name: Configure Redis for Fleet
  ansible.builtin.template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: '0640'
    backup: true
  notify: Restart redis

- name: Enable Redis
  ansible.builtin.systemd:
    name: redis-server
    state: started
    enabled: true
