fleet_version: "latest"
fleet_server_url: "http://192.168.68.240:8080"
fleet_db_host: "192.168.68.241"
fleet_redis_host: "192.168.68.242"
fleet_db_name: "fleet"
fleet_db_user: "fleet"
fleet_db_password: "CHANGE_ME_DB_PASSWORD"
fleet_jwt_key: "CHANGE_ME_LONG_RANDOM_SECRET"
fleet_enroll_secret: "CHANGE_ME_AFTER_FIRST_SETUP"
