fleet_version: "latest"
fleet_domain: "fleet.example.local"
fleet_server_url: "https://fleet.example.local:8080"
fleet_mysql_database: "fleet"
fleet_mysql_user: "fleet"
fleet_mysql_password: "CHANGE_ME_USE_ANSIBLE_VAULT"
fleet_mysql_address: "{{ hostvars[groups['fleet_db'][0]].ansible_host }}:3306"
fleet_redis_address: "{{ hostvars[groups['fleet_redis'][0]].ansible_host }}:6379"
fleet_server_private_key: "CHANGE_ME_USE_ANSIBLE_VAULT_32_PLUS_CHARS"
fleet_tls_cert_path: "/etc/fleet/certs/fleet.crt"
fleet_tls_key_path: "/etc/fleet/certs/fleet.key"
